<?php

/**
 * @file
 * Contains az_content.module.
 */

use Drupal\az_groups\azGroupQuery;
use Drupal\comment\Entity\Comment;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\Component\Utility\Random;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_theme().
 */
function az_content_theme() {
  return [
    'block_donate' => [
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'more_url' => NULL,
      ],
    ],
    'block_contribute' => [
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'more_url' => NULL,
      ],
    ],
  ];
}
/**
 * Implements hook_form_alter().
 */
function az_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return;
}

function az_content_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();
  $type = $node->getType();
  if (in_array($type, ['article', 'book', 'news'])) {
    $form['mailit'] = [
      '#type' => 'container',
      'checkbox' => [
        '#type' => 'checkbox',
        '#title' => t('Send email notification'),
        '#default_value' => false,
      ],
    ];
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_az_content_node_submit';
      }
    }
  }
}

function _az_content_node_submit(&$form, FormStateInterface &$form_state) {
  return;
}

function az_content_form_node_ticket_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $request = \Drupal::request();
  if ($request->query->has('group')) {
    $gid = $request->query->get('group');
    $group = \Drupal::entityTypeManager()->getStorage('group')->load($gid);
    $form['field_group']['widget'][0]['target_id']['#default_value'] = $group;
  }

  if ($request->query->has('node')) {
    $nid = $request->query->get('node');
    $node = is_numeric($nid) ? Node::load($nid) : NULL;
    $form['field_page']['widget'][0]['target_id']['#default_value'] = $node;
  }
}

/**
 * Implements hook_node_presave().
 */
function az_content_node_presave(Node $node) {
  if  ($node->getType() == 'article' || $node->getType() == 'book') {

    // If this page belongs to a book, and the book is in a group, create group content reference.
    if (5) {

    }

    // If there is a primary image add reference back to the page.
    if ($node->hasField('field_media')) {
      $mediaRef = $node->field_media;
      $value = $mediaRef->getValue();
      if (!empty($value[0])) {
        $media = \Drupal::entityManager()->getStorage('media')->load($value[0]['target_id']);
        if ($media != null) {
          _az_content_add_node_to_media($media, $node->id());
        }
      }
    }

    // Find media in body and create reference back to the page.
    $bodyValue = $node->get('body')->getValue();
    if (!empty($bodyValue[0])) {
      preg_match_all("/data-entity-uuid=\".*?\"/", $bodyValue[0]['value'], $matches);
      foreach($matches[0] as $match) {
        $uuid = explode('"', $match)[1];
        $media = \Drupal::entityManager()->loadEntityByUuid('media', $uuid);
        if ($media != null) {
          _az_content_add_node_to_media($media, $node->id());
        }
      }
    }
  }
  return;
}

/**
 * Implements HOOK_entity_presave().
 *
 */
function az_content_entity_presave(EntityInterface $entity) {
  return;
}

/**
 * Implement HOOK_comment_presave().
 *
 * @param \Drupal\comment\Entity\Comment $comment
 */
function az_content_comment_presave(Comment $comment) {
  $articleId = $comment->get('entity_id')->getValue()[0]['target_id'];
  $bodyRef = $comment->get('comment_body');
  $bodyValue = $bodyRef->getValue();
  if (!empty($bodyValue[0])) {
    preg_match_all("/data-entity-uuid=\".*?\"/", $bodyValue[0]['value'], $matches);
    foreach($matches[0] as $match) {
      $uuid = explode('"', $match)[1];
      $media = \Drupal::entityManager()->loadEntityByUuid('media', $uuid);
      _az_content_add_node_to_media($media, $articleId);
    }
  }
  return;
}

/**
 * Implements HOOK_media_presave().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function az_content_media_presave(EntityInterface $entity) {
  return;
}

/**
 * Implements HOOK_file_presave().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function az_content_file_presave(EntityInterface $entity) {
  return;
}

/**
 * Implements HOOK_preprocess_page().
 *
 * If this is the structuredatom.com and the user is not logged in then redirect
 * to the /under-construction.
 *
 * @param $variables
 */
function az_content_preprocess_page(&$variables) {

  if ($_SERVER['HTTP_HOST'] == 'atom' ||
      $_SERVER['HTTP_HOST'] == 'structuredatom.org' ||
      $_SERVER['HTTP_HOST'] == 'structuredatom.com') {
    if (\Drupal::currentUser()->isAnonymous() &&
        strstr($_SERVER['REQUEST_URI'], 'under-construction') == null  &&
        strstr($_SERVER['REQUEST_URI'], 'user/login') == null  &&
        strstr($_SERVER['REQUEST_URI'], 'user/password') == null) {
      drupal_set_message(t('The Structured Atom site is currently under construction ...'), 'status', TRUE);
      $response = new RedirectResponse('/under-construction');
      $response->send();
    }
  }
  return;
}

/**
 * Add a node reference to the media entity field_usage field.
 *
 * @param $media
 * @param $articleId
 */
function _az_content_add_node_to_media($media, $articleId) {
  $articles = $media->get('field_usage');
  $found = false;
  if (!empty($articles)) {
    $values = $articles->getValue();
    foreach ($values as $value) {
      if ($value['target_id'] == $articleId) {
        $found = TRUE;
      }
    }
  }
  if (!$found) {
    $media->field_usage->appendItem($articleId);
    $media->save();
  }
}

/**
 * Implements HOOK_preprocess_block().
 *
 * @param $variables
 */
function az_content_preprocess_block(&$variables) {
  switch ($variables['plugin_id']) {
    case 'az_top_nav_block':
      $snippet = \Drupal::entityManager()->getStorage('node')->load(377);
      $build = \Drupal::entityTypeManager()->getViewBuilder('node')->view($snippet, 'full');
      $variables['logo_popup'] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['popup']],
        'contents' => $build,
      ];
      break;
  }
  return;
}

/**
 * Implements HOOK_preprocess_node().
 *
 * @param $variables
 */
function az_content_preprocess_node(&$variables) {
  // Add marker if content is New, Updated or has already been read.
  $node = $variables['node'];
  $type = $node->getType();
  $view_mode = &drupal_static('az_view_mode');
  $view_mode = $variables['view_mode'];

  $variables['bundle_name'] = $node->type->entity->label();

  if ($view_mode == 'full' || $view_mode == 'teaser') {
    // Add marker if content is New, Updated or has already been read.
    switch (node_mark($variables['node']->id(), $variables['node']->getChangedTime())) {
      case 0:
        $mark = '';
        break;
      case 1:
        $mark = 'New';
        break;
      case 2:
        $mark = 'Updated';
        break;
    };
    $variables['has_new_content'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['marker'],
      ],
      'label' => ['#markup' => $mark],
    ];
  }

  switch ($type) {
    case 'article':
    case 'book':
    case 'news':
    case 'page':
    case 'glossary':

      // Use Changed time to format date and ago.
      $changed = $node->getChangedTime();
      $variables['changed'] = \Drupal::service('date.formatter')->format($changed);
      $variables['ago'] = \Drupal::service('date.formatter')->formatDiff(
        $changed,
        REQUEST_TIME,
        [
          'granularity' => 2,
          'return_as_object' => TRUE,
        ]
      );

      // Add the New/Updated marker.
      if ($view_mode == 'main_content' || $view_mode == 'full' || $view_mode == 'teaser') {
        // Query to see if this content is in a group
        // if so load group and add to output.
        if ($gid = azGroupQuery::inGroup($node)) {
          $group = \Drupal::entityManager()->getStorage('group')->load($gid);
          $variables['group_url'] = \Drupal::service('path.alias_manager')->getAliasByPath('/group/'.$gid);
          $variables['group_label'] = $group->label->value;
        }
      }

      if ($view_mode == 'full') {
        if (in_array($type, ['article', 'news', 'book'])) {
          // Create book navigation block
          $block_entity = Drupal\block\Entity\Block::load('azbooknavigation');
          $variables['sidebar_blocks']['block_booknavigation'] = \Drupal::entityTypeManager()
            ->getViewBuilder('block')
            ->view($block_entity);

          // Add the contribute block if this nodes field_contribute has a value.
          if ($node->hasField('field_contribute') && !$node->field_contribute->isEmpty()) {
            $block_entity = Drupal\block\Entity\Block::load('azcontributeblock');
            $variables['sidebar_blocks']['block_contribute'] = \Drupal::entityTypeManager()
              ->getViewBuilder('block')
              ->view($block_entity);
          }

          // Add the views map showing locations of images
          if ($node->hasField('field_display_image_map') && !$node->field_display_image_map->isEmpty()) {
            $block_entity = Drupal\block\Entity\Block::load('views_block__az_media_block_map_usage');
            $variables['sidebar_blocks']['block_views_image_map'] = \Drupal::entityTypeManager()
              ->getViewBuilder('block')
              ->view($block_entity);
          }
        }

        if ($type == 'glossary') {
          $variables['sidebar_blocks']['view_recent_content'] = [
            '#type' => 'container',
            '#attributes' => ['class' => ['block-sidebar']],
            'title' => [
              '#type' => 'container',
              '#attributes' => ['class' => ['title-container']],
              'markup' => ['#markup' => '<h2>Recent Activity</h2>'],
            ],
            'content' => [
              '#type' => 'container',
              '#attributes' => ['class' => ['content-container']],
              'markup' => views_embed_view('content_recent', 'block_topic'),
            ],
          ];
        }

        // Add the Donate block.
        $block_entity = Drupal\block\Entity\Block::load('azdonateblock');
        $variables['sidebar_blocks']['block_donate'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);
      }

      break;

    case 'landing_page':

      // Dashboard - Front page
      if (\Drupal::service('path.matcher')->isFrontPage()) {
        $user = User::load(\Drupal::currentUser()->id());
        $id = $user->id();
        if ($id != 0) {
          $variables['user_id'] = $user->id();
          $variables['user_name'] = $user->name->value;
          $picture = $user->field_picture->getValue();
          $file = \Drupal\file\Entity\File::load($picture[0]['target_id']);
          $variables['user_picture_url'] = \Drupal\image\Entity\ImageStyle::load('thumbnail')->buildUrl($file->getFileUri());

          $variables['view_my_groups'] = views_embed_view('az_my_groups', 'user_block');
          $variables['view_my_activity'] = views_embed_view('az_my_activity', 'user_block');
          $variables['view_my_comments'] = views_embed_view('az_my_comments', 'user_block');
          $variables['view_my_media'] = views_embed_view('az_media', 'user_block');

          if (AccessResult::allowedIfHasPermission($user, 'view any unpublished content')) {
            $variables['view_content_unpublished'] = views_embed_view('content_recent', 'block_unpublished');
          }
        }
        else {
          $snippet = \Drupal::entityManager()->getStorage('node')->load(325);
          $variables['dashboard_block'] = \Drupal::entityTypeManager()->getViewBuilder('node')->view($snippet, 'full');
        }

        $variables['view_content_recent'] = views_embed_view('content_recent', 'block_all');
        $variables['view_comments_recent'] = views_embed_view('comments_recent', 'block_all');

        if ($node->hasField('field_announcement')) {
          $nid = $node->field_announcement->getValue()[0]['target_id'];
          $snippet = \Drupal::entityManager()->getStorage('node')->load($nid);
          $variables['section_announcement'] = \Drupal::entityTypeManager()->getViewBuilder('node')->view($snippet, 'full');
        }

        $block_entity = Drupal\block\Entity\Block::load('azdonateblock');
        $variables['block_donate'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);
      }
      break;
  }
}

/**
 * Alter the results of the particular embedded entity type build array.
 *
 * @param array &$build
 *   A renderable array representing the embedded entity content.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The embedded entity object.
 * @param array $context
 *   The context array.
 */
function az_content_entity_embed_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, array &$context) {
  if (!empty($build['entity']['#view_mode'])) {
    $build['#attributes']['class'][] = 'az-view-mode-' . str_replace('_', '-', $build['entity']['#view_mode']);
  }
}

/**
 * Implements HOOK_preprocess_ENTITY-TYPE().
 *
 * @param $variables
 */
function az_content_preprocess_media(&$variables) {
  $variables['attributes']['class'][] = 'az-view-mode-' . str_replace('_', '-', $variables['elements']['#view_mode']);
  return;
}

//////////////////////// Start entity_embed module api functions

/**
 * @addtogroup hooks
 * @{
 */

/**
 * Alter the Entity Embed Display plugin definitions.
 *
 * @param array &$info
 *   An associative array containing the plugin definitions keyed by plugin ID.
 */
function az_content_entity_embed_display_plugins_alter(array &$info) {
  return;
}

/**
 * Alter the Entity Embed Display plugin definitions for a given context.
 *
 * Usually used to remove certain Entity Embed Display plugins for specific
 * entities.
 *
 * @param array &$definitions
 *   Remove options from this list if they should not be available for the given
 *   context.
 * @param array $contexts
 *   The provided context, typically an entity.
 */
function az_content_entity_embed_display_plugins_for_context_alter(array &$definitions, array $contexts) {
  return;  // Return - testing this hook
  // Do nothing if no entity is provided.
  if (!isset($contexts['entity'])) {
    return;
  }
  $entity = $contexts['entity'];

  // For video and audio files, limit the available options to the media player.
  if ($entity instanceof \Drupal\file\FileInterface && in_array($entity->bundle(), ['audio', 'video'])) {
    $definitions = array_intersect_key($definitions, array_flip(['file:jwplayer_formatter']));
  }

  // For images, use the image formatter.
  if ($entity instanceof \Drupal\file\FileInterface && in_array($entity->bundle(), ['image'])) {
    $definitions = array_intersect_key($definitions, array_flip(['image:image']));
  }

  // For nodes, use the default option.
  if ($entity instanceof \Drupal\node\NodeInterface) {
    $definitions = array_intersect_key($definitions, array_flip(['entity_reference:entity_reference_entity_view']));
  }
}

/**
 * Alter the context of an embedded entity before it is rendered.
 *
 * @param array &$context
 *   The context array.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity object.
 */
function az_content_entity_embed_context_alter(array &$context, \Drupal\Core\Entity\EntityInterface $entity) {
  return;
}

/**
 * Alter the context of an particular embedded entity type before it is rendered.
 *
 * @param array &$context
 *   The context array.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity object.
 */
function az_content_node_embed_context_alter(array &$context, \Drupal\Core\Entity\EntityInterface $entity) {
  return;
}

