<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * @file
 * Contains az_groups.module.
 */

function az_groups_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  /**
   * Attempting to add groups and roles to the node form - on hold for now
  // Query for all groups.
  $query = \Drupal::database()->select('groups_field_data', 'gfd');
  $query->addField('gfd', 'id');
  $query->addField('gfd', 'label');
  $query->orderBy('gfd.label', 'ASC');
  $results = $query->execute()->fetchAllAssoc('id');

  // Set up groups array
  $groups = ['0' => 'None'];
  foreach($results as $result) {
    $groups[$result->id] = $result->label;
  }

  // Query for roles current user has in this? group.  WTF.  This ain't no fun.

  $form['group'] = [
    '#type' => 'fieldset',
    '#title' => t('Community'),
    'group_id' => [
      '#type' => 'select',
      '#title' => 'Community',
      '#default_value' => '0',
      '#options' => $groups,
    ],
    'group_role' => [
      '#type' => 'select',
      '#title' => 'Community Role',
      '#description' => 'Select the role that can view this post',
      '#options' => $options,
    ],
  ];

  $form['actions']['submit']['#submit'][] = '_az_groups_node_form_submit';
  **/
  return;
}

function _az_groups_node_form_submit($form, FormStateInterface $form_state) {
  $group = $form_state->getValue('group');
  return;
}

function az_groups_preprocess_group(&$variables) {

  $group = &$variables['group'];
  $az_wysiwyg = &drupal_static('az_wysiwyg', null);  // Save statically - used by WysiwygFilter
  $az_wysiwyg = [
    'group' => $group->id(),
    'view_mode' => $variables['view_mode'],
  ];

  // Show SAM status block - shown in sidebar.
  if ($group->label() == 'Structured Atom Model') {
    $build = \Drupal::entityTypeManager()->getViewBuilder('node')->view(Node::load(425), 'full');
    $variables['community_status'] = $build;
  }

  $block_entity = Drupal\block\Entity\Block::load('groupoperations');
  $variables['block_groupoperations'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);

  $block_entity = Drupal\block\Entity\Block::load('azbooknavigation');
  $variables['block_booknavigation'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);

  $variables['view_group_members'] = views_embed_view('group_members', 'group_members');

  $home = _az_content_build_content_tab([
    'type' => 'entity-render',
    'id' => 'home',
    'tab' => 'Home',
//  'title' => '<h2>Home</h2>',
    'viewMode' => 'home_tab',
    'entityType' => 'group',
    'eid' => $group->id(),
  ]);

  // Create Recent Activity tab
  $activity = _az_content_build_content_tab([
    'type' => 'entity-stream',
    'id' => 'recent-activity',
    'tab' => 'Activity',
    'types' => ['article', 'event', 'book', 'news'],
    'groups' => $group->id(),
    'title' => 'Recent Activity',
    'status' => NODE_PUBLISHED,
    'empty' => 'No activity for this site',
  ]);

  // Create Recent Comments tab
  $comments = _az_content_build_content_tab([
    'type' => 'entity-stream',
    'id' => 'recent-comments',
    'tab' => 'Comments',
    'title' => 'Recent Comments',
    'entityType' => 'comment',
    'types' => 'UNSET',
    'empty' => 'No comments posted for this community',
  ]);

  $variables['tabs'] = [
    'home'     => (isset($home))     ? $home     : null,
    'activity' => (isset($activity)) ? $activity : null,
    'comments' => (isset($comments)) ? $comments : null,
  ];

  return;
}


