<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains az_groups.module.
 */

function az_groups_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return;
}

function az_groups_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  /**
   * Attempting to add groups and roles to the node form - on hold for now
  // Query for all groups.
  $query = \Drupal::database()->select('groups_field_data', 'gfd');
  $query->addField('gfd', 'id');
  $query->addField('gfd', 'label');
  $query->orderBy('gfd.label', 'ASC');
  $results = $query->execute()->fetchAllAssoc('id');

  // Set up groups array
  $groups = ['0' => 'None'];
  foreach($results as $result) {
    $groups[$result->id] = $result->label;
  }

  // Query for roles current user has in this? group.  WTF.  This ain't no fun.

  $form['group'] = [
    '#type' => 'fieldset',
    '#title' => t('Community'),
    'group_id' => [
      '#type' => 'select',
      '#title' => 'Community',
      '#default_value' => '0',
      '#options' => $groups,
    ],
    'group_role' => [
      '#type' => 'select',
      '#title' => 'Community Role',
      '#description' => 'Select the role that can view this post',
      '#options' => $options,
    ],
  ];

  $form['actions']['submit']['#submit'][] = '_az_groups_node_form_submit';
  **/
  return;
}

function _az_groups_node_form_submit($form, FormStateInterface $form_state) {
  $group = $form_state->getValue('group');
  return;
}

function az_groups_preprocess_node(&$variables) {
  return;
}

function az_groups_preprocess_group(&$variables) {

  $block_entity = Drupal\block\Entity\Block::load('groupoperations');
  $variables['block_groupoperations'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);

  $block_entity = Drupal\block\Entity\Block::load('azdonateblock');
  $variables['block_donate'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);

  $block_entity = Drupal\block\Entity\Block::load('azbooknavigation');
  $variables['block_booknavigation'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);

  $variables['view_group_members'] = views_embed_view('group_members', 'group_members');

  $variables['view_group_content'] = views_embed_view('az_group_activity', 'teaser_block');
  return;
}

function az_groups_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'account' && $variables['logged_in']) {
    $user = \Drupal::entityTypeManager()
      ->getStorage('user')
      ->load(\Drupal::currentUser()->id());
    if ($user) {
      if ($user->field_picture->isEmpty()) {
        $variables['user_name'] = $user->name;
      }
      else {
        $picture = $user->field_picture->getValue();
        $file = \Drupal\file\Entity\File::load($picture[0]['target_id']);
        $variables['user_picture_url'] = \Drupal\image\Entity\ImageStyle::load('thumbnail')->buildUrl($file->getFileUri());
      }
    }
  }

  return;
}
