<?php

/**
 * @file
 * Contains az_user.module.
 */

use Drupal\Component\Utility\Random;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_form_FORM_ID_alter().   user_form
 */
function az_user_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!\Drupal::currentUser()->hasPermission('administer account settings')) {
    $form['field_address']['#access'] = false;
    $form['field_phone']['#access'] = false;
    $form['field_private_notes']['#access'] = false;
  }
  return;
}

/**
 * Implements hook_form_FORM_ID_alter().   user_login
 */
function az_user_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $form['login-form'] = [
    '#type' => 'container',
    '#weight' => 0,
    '#attributes' => ['class' => ['login-form']],
    'name' => $form['name'],
    'pass' => $form['pass'],
    'header' => [
      '#type' => 'container',
      '#attributes' => ['class' => ['header']],
      '#weight' => -1,
      'markup' => ['#markup' => '<h2>Login to Ethereal Matters</h2>'],
    ],
    'forgot_password' => [
      '#type' => 'container',
      '#attributes' => ['class' => ['forgot-password']],
      '#weight' => 101,
      'markup' => ['#markup' => 'Forgot your password? - <a href="/user/register">Click here</a>'],
    ],
    'actions' => $form['actions'],
  ];
  unset($form['name']);
  unset($form['pass']);
  unset($form['actions']);

  // Add the join block that goes below the login form.   nid 321
  $build = \Drupal::entityTypeManager()->getViewBuilder('node')->view(Node::load(321), 'full');
  $form['join_block'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['join-block']],
    '#weight' => 100,
    'markup' => ['#markup' => render($build)],
  ];

  return;
}

/**
 * Implements HOOK_preprocess_user().
 *
 */
function az_user_preprocess_user(&$variables) {
  $user = $variables['user'];

  // Create the fullname by concatenating the first and last names.
  if (!empty($variables['content']['field_first_name'])) {
    $variables['fullname'] = $variables['content']['field_first_name']['0']['#context']['value'] . ' ';
  }
  if (!empty($variables['content']['field_last_name'])) {
    $variables['fullname'] .= $variables['content']['field_last_name']['0']['#context']['value'];
  }

  // Get the URL of the user
  $variables['url'] = $variables['user']->url();

  // Create Users Recent Activity tab
  $activity = [
    'type' => 'entity-stream',
    'id' => 'recent-activity',
    'label' => 'Activity',
    'title' => 'Activity',
    'author' => $user->id(),
    'status' => NODE_PUBLISHED,
    'empty' => 'No activity for this user',
  ];

  // Create Users Unpublished tab
  $unpublished = [
    'type' => 'entity-stream',
    'id' => 'unpublished-activity',
    'label' => 'Unpublished',
    'title' => 'Recent Unpublished Activity',
    'author' => $user->id(),
    'status' => NODE_NOT_PUBLISHED,
    'empty' => 'No unpublished activity for this user',
  ];

  // Create Users Tickets tab
  if (\Drupal::currentUser()->hasPermission('az content view tickets')) {
    $tickets = [
      'type' => 'entity-stream',
      'id' => 'tickets',
      'label' => 'Tickets',
      'types' => 'ticket',
      'title' => 'Tickets I created',
      'author' => $user->id(),
      'empty' => 'NO DISPLAY',
    ];

    $assigned = [
      'type' => 'entity-stream',
      'id' => 'assigned',
      'label' => 'Assigned Tickets',
      'types' => 'ticket',
      'title' => 'Tickets Assigned to Me',
      'assigned' => $user->id(),
      'empty' => 'NO DISPLAY',
    ];
  }

  // Create Users Comments tab
  $comments = [
    'type' => 'entity-stream',
    'entityType' => 'comment',
    'id' => 'comments',
    'label' => 'Comments',
    'authorComment' => $user->id(),
    'title' => 'Comments',
    'status' => NODE_PUBLISHED,
    'empty' => 'No comments for this user',
  ];

  $sets = [];
  if (isset($activity))    $sets[$activity['id']]    = $activity;
  if (isset($unpublished)) $sets[$unpublished['id']] = $unpublished;
  if (isset($tickets))     $sets[$tickets['id']]     = $tickets;
  if (isset($assigned))    $sets[$assigned['id']]    = $assigned;
  if (isset($comments))    $sets[$comments['id']]    = $comments;
  $variables['tabs'] = _az_content_build_tabs('main', $sets);
}

function az_user_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'account' && $variables['logged_in']) {
    $user = \Drupal::entityTypeManager()
      ->getStorage('user')
      ->load(\Drupal::currentUser()->id());
    if ($user) {
      if ($user->field_picture->isEmpty()) {
        $variables['user_name'] = $user->name[0]->value;
      }
      else {
        $fid = $user->field_picture[0]->target_id;
        $file = \Drupal\file\Entity\File::load($fid);
        $variables['user_picture_url'] = \Drupal\image\Entity\ImageStyle::load('thumbnail')->buildUrl($file->getFileUri());
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter
 *
 * Suggest user--{view_mode}.html.twig file.
 */
function az_user_theme_suggestions_user_alter(array &$suggestions, array $variables, $hook) {
  $suggestions[] = $variables['theme_hook_original'] . '__' . str_replace('-', '_', $variables['elements']['#view_mode']);
  return $suggestions;
}
