<?php

/**
 * @file
 * Enables Group functionality for the Media module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\group\Entity\GroupContentType;
use Drupal\group\Entity\GroupRoleInterface;
use Drupal\media\MediaInterface;
use Drupal\media\MediaTypeInterface;

// We need a grant ID for match-all access records.
define('GNODE_MASTER_GRANT_ID', 1986);

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gmedia_media_type_insert(MediaTypeInterface $media_type) {
  \Drupal::service('plugin.manager.group_content_enabler')->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gmedia_group_role_insert(GroupRoleInterface $group_role) {
  // Because we optimize for anonymous users, it also means we need to rebuild
  // the media grants table when an anonymous role is added.
  // See: gmedia_media_access_records()
  if ($group_role->isAnonymous()) {
    media_access_needs_rebuild(TRUE);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function gmedia_group_role_update(GroupRoleInterface $group_role) {
  // Because we optimize for anonymous users, it also means we need to rebuild
  // the media grants table when an anonymous role has its permissions changed.
  // See: gmedia_media_access_records()
  if ($group_role->isAnonymous()) {
    $new = array_unique($group_role->getPermissions());
    $old = array_unique($group_role->original->getPermissions());
    sort($new);
    sort($old);

    if ($new != $old) {
      media_access_needs_rebuild(TRUE);
    }
  }
}

/**
 * Implements hook_media_access().
 *
 * When trying to view, update or delete a media it suffices to have the right to
 * do so in only one group the media belongs to. If you wish to prevent any such
 * action on your own terms, implement hook_media_access() in your module.
 */
function gmedia_media_access(MediaInterface $media, $op, AccountInterface $account) {
  // We do not care about create access as we have our own wizard for that. Any
  // operation aside from 'view', 'update' and 'delete' is also unsupported.
  if (!in_array($op, ['view', 'update', 'delete'])) {
    return AccessResult::neutral();
  }

  // Some modules, including the code in \Drupal\media\MediaForm::access() may
  // check for 'view', 'update' or 'delete' access on new media, even though
  // that makes little sense. We need to account for it to avoid crashes because
  // we would otherwise query the DB with a non-existent media ID.
  if ($media->isNew()) {
    return AccessResult::neutral();
  }

  $plugin_id = 'group_media:' . $media->bundle();

  // Only act if there are group content types for this media type.
  $group_content_types = GroupContentType::loadByContentPluginId($plugin_id);
  if (empty($group_content_types)) {
    return AccessResult::neutral();
  }

  // Load all the group content for this media.
  $group_contents = \Drupal::entityTypeManager()
    ->getStorage('group_content')
    ->loadByProperties([
      'type' => array_keys($group_content_types),
      'entity_id' => $media->id(),
    ]);

  // If the media does not belong to any group, we have nothing to say.
  if (empty($group_contents)) {
    return AccessResult::neutral();
  }

  /** @var \Drupal\group\Entity\GroupInterface[] $groups */
  $groups = [];
  foreach ($group_contents as $group_content) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group = $group_content->getGroup();
    $groups[$group->id()] = $group;
  }

  // From this point on you need group to allow you to perform the operation.
  switch ($op) {
    case 'view':
      foreach ($groups as $group) {
        if ($media->isPublished()) {
          if ($group->hasPermission("view $plugin_id entity", $account)) {
            return AccessResult::allowed();
          }
        }
        elseif ($group->hasPermission("view unpublished $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
      }
      break;

    case 'update':
    case 'delete':
      foreach ($groups as $group) {
        if ($group->hasPermission("$op any $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
        elseif ($account->id() == $media->getOwnerId() && $group->hasPermission("$op own $plugin_id entity", $account)) {
          return AccessResult::allowed();
        }
      }
      break;
  }

  // Instead of outright forbidding access when no group granted it, we return
  // a neutral access result to play nice with other modules. If the end result
  // is still neutral, Drupal will deny access anyway unless the media grants
  // system allows the operation in a last ditch effort to determine access.
  return AccessResult::neutral();
}

/**
 * Implements hook_media_grants().
 *
 * We define the following grants:
 * - 'gmedia:NODE_TYPE': Grants view and update or delete any access to media.
 * - 'gmedia_unpublished:NODE_TYPE': Grants view access to unpublished media.
 * - 'gmedia_author:UID:NODE_TYPE': Grants update or delete access to authors.
 * - 'gmedia_anonymous': Given to anonymous users.
 * - 'gmedia_bypass': Given to anyone with the 'bypass group access' permission.
 *
 * @see gmedia_media_access_records()
 */
function gmedia_media_grants(AccountInterface $account, $op) {
  // Provide the master grant for users who can bypass group access.
  if ($account->hasPermission('bypass group access')) {
    return ['gmedia_bypass' => [GNODE_MASTER_GRANT_ID]];
  }

  // Anonymous users get the anonymous grant. See the implementation in the
  // gmedia_media_access_records() function as to why that is.
  if ($account->isAnonymous()) {
    return ['gmedia_anonymous' => [GNODE_MASTER_GRANT_ID]];
  }

  // Gather the machine names of all media types.
  $entity_type_manager = \Drupal::entityTypeManager();
  $media_type_ids = $entity_type_manager
    ->getStorage('media_type')
    ->getQuery()
    ->execute();

  // Initialize a grant array for members and one for outsider users.
  $grants_m = $grants_o = [];

  // If the user could not bypass group access, we need to check their access
  // for every single group. Because loading every group would incur a massive
  // performance hit, we only load those groups the user is a member of.
  /** @var \Drupal\group\GroupMembershipLoaderInterface $membership_loader */
  $membership_loader = \Drupal::service('group.membership_loader');
  foreach ($membership_loader->loadByUser($account) as $group_membership) {
    $group = $group_membership->getGroup();

    // Add the groups the user is a member of to use later on.
    $member_gids[] = $gid = $group->id();

    foreach ($media_type_ids as $media_type_id) {
      $plugin_id = "group_media:$media_type_id";

      switch ($op) {
        case 'view':
          if ($group->hasPermission("view $plugin_id entity", $account)) {
            $grants_m["gmedia:$media_type_id"][] = $gid;
          }
          if ($group->hasPermission("view unpublished $plugin_id entity", $account)) {
            $grants_m["gmedia_unpublished:$media_type_id"][] = $gid;
          }
          break;

        case 'update':
        case 'delete':
          // If you can act on any media, there's no need for the author grant.
          if ($group->hasPermission("$op any $plugin_id entity", $account)) {
            $grants_m["gmedia:$media_type_id"][] = $gid;
          }
          elseif ($group->hasPermission("$op own $plugin_id entity", $account)) {
            $uid = $account->id();
            $grants_m["gmedia_author:$uid:$media_type_id"][] = $gid;
          }
          break;
      }
    }
  }

  // All other groups have the benefit of sharing the same permission set among
  // all authenticated users per group type. We can therefore know the user's
  // permissions for all groups of the same group type they aren't part of.
  /** @var \Drupal\group\Entity\GroupTypeInterface[] $group_types */
  $group_types = $entity_type_manager->getStorage('group_type')->loadMultiple();
  foreach ($group_types as $group_type) {
    // Get the IDs of all the groups the user is not part of for the group type.
    $query = $entity_type_manager->getStorage('group')->getQuery();
    $query->condition('type', $group_type->id());
    if (!empty($member_gids)) {
      $query->condition('id', $member_gids, 'NOT IN');
    }
    $gids = $query->execute();

    // If we could not retrieve any group IDs, skip to the next group type.
    if (empty($gids)) {
      continue;
    }

    // Grab the outsider role for the group type.
    $group_role = $group_type->getOutsiderRole();

    foreach ($media_type_ids as $media_type_id) {
      $plugin_id = "group_media:$media_type_id";

      // Only check for permissions if the group type has the group_media plugin
      // installed for the media type.
      if (!$group_type->hasContentPlugin($plugin_id)) {
        continue;
      }

      switch ($op) {
        case 'view':
          if ($group_role->hasPermission("view $plugin_id entity")) {
            $grants_o["gmedia:$media_type_id"][] = $gids;
          }
          if ($group_role->hasPermission("view unpublished $plugin_id entity")) {
            $grants_o["gmedia_unpublished:$media_type_id"][] = $gids;
          }
          break;

        case 'update':
        case 'delete':
          // If you can act on any media, there's no need for the author grant.
          if ($group_role->hasPermission("$op any $plugin_id entity")) {
            $grants_o["gmedia:$media_type_id"][] = $gids;
          }
          elseif ($group_role->hasPermission("$op own $plugin_id entity")) {
            $uid = $account->id();
            $grants_o["gmedia_author:$uid:$media_type_id"][] = $gids;
          }
          break;
      }
    }
  }

  // The code above populated the outsider grants by adding the group IDs per
  // group type. We need to combine this into one big list of group IDs per
  // entry in the $grants_o array.
  foreach ($grants_o as $key => $gids_per_group_type) {
    $grants_o[$key] = array_reduce($gids_per_group_type, 'array_merge', []);
  }

  // Recursively merge the member grants with the outsider grants.
  return array_merge_recursive($grants_m, $grants_o);
}

/**
 * Implements hook_media_access_records().
 *
 * @see gmedia_media_grants()
 */
function gmedia_media_access_records(MediaInterface $media) {
  $records = $group_types = [];
  $media_type_id = $media->bundle();
  $plugin_id = "group_media:$media_type_id";

  // Only act if there are group content types for this media type.
  $group_content_types = GroupContentType::loadByContentPluginId($plugin_id);
  if (empty($group_content_types)) {
    return $records;
  }

  // Load all of the group content for this media.
  $group_contents = \Drupal::entityTypeManager()
    ->getStorage('group_content')
    ->loadByProperties([
      'type' => array_keys($group_content_types),
      'entity_id' => $media->id()
    ]);

  // Only act if there are group content entities for this media.
  if (empty($group_contents)) {
    return $records;
  }

  // We can use the same grant-all base because we will only hand out the grants
  // based on the $op parameter in hook_media_grants().
  $base = [
    'grant_view' => 1,
    'grant_update' => 1,
    'grant_delete' => 1,
    'priority' => 0,
  ];

  // Set records for every group the media belongs to.
  $uid = $media->getOwnerId();
  $prefix = $media->isPublished() ? 'gmedia' : 'gmedia_unpublished';
  foreach ($group_contents as $group_content) {
    /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
    $group = $group_content->getGroup();
    $group_type_id = $group_content->bundle();

    // Gather all group types the media belongs to.
    if (!isset($group_types[$group_type_id])) {
      $group_types[$group_type_id] = $group->getGroupType();
    }

    // We use the group ID as the realm ID.
    $gid = $group->id();

    // Add the non-author record for viewing media.
    $records[] = ['gid' => $gid, 'realm' => "$prefix:$media_type_id"] + $base;

    // Add the author record for updating or deleting.
    $records[] = ['gid' => $gid, 'realm' => "gmedia_author:$uid:$media_type_id"] + $base;
  }

  // Add the general access bypass record.
  $records[] = ['gid' => GNODE_MASTER_GRANT_ID, 'realm' => 'gmedia_bypass'] + $base;

  // For anonymous users we actually build the access record based on the groups
  // the media belongs to. After all: If you're anonymous to one group, you're
  // anonymous to all groups. Meaning that if one of the media's groups allows
  // anonymous users to view the media, all anonymous users can view it. We can
  // use this to our advantage by assigning a special access record that we can
  // provide a grant for in gmedia_media_grants().
  $anonymous_record = [
    'gid' => GNODE_MASTER_GRANT_ID,
    'realm' => 'gmedia_anonymous',
    'grant_view' => 0,
    'grant_update' => 0,
    'grant_delete' => 0,
    'priority' => 0,
  ];

  // Get references to the grants for faster and more readable loops below.
  $can_view = &$anonymous_record['grant_view'];
  $can_update = &$anonymous_record['grant_update'];
  $can_delete = &$anonymous_record['grant_delete'];

  $view_permission = $media->isPublished()
    ? "view $plugin_id entity"
    : "view unpublished $plugin_id entity";

  foreach ($group_types as $group_type) {
    /** @var \Drupal\group\Entity\GroupTypeInterface $group_type */
    $group_role = $group_type->getAnonymousRole();

    if (!$can_view && $group_role->hasPermission($view_permission)) {
      $can_view = 1;
    }
    if (!$can_update && $group_role->hasPermission("update any $plugin_id entity")) {
      $can_update = 1;
    }
    if (!$can_delete && $group_role->hasPermission("delete any $plugin_id entity")) {
      $can_delete = 1;
    }

    // If the media is owned by anonymous, we also need to check for the author
    // permissions following the pattern "$op own $plugin_id entity".
    if ($uid == 0) {
      if (!$can_update && $group_role->hasPermission("update own $plugin_id entity")) {
        $can_update = 1;
      }
      if (!$can_delete && $group_role->hasPermission("delete own $plugin_id entity")) {
        $can_delete = 1;
      }
    }
  }

  $records[] = $anonymous_record;

  return $records;
}
