https://www.{default}/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
http://structuredatom.org/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
http://realscience.rocks/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
