https://www.{default}/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
https://realscience.rocks/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
https://eugeology.rocks/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  to: https://etherealmatters.org
https://RealScience.Rocks/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
https://structuredatom.org/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
https://etherealmatters.org/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
https://etherealmatters.com/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
