<?php


/**
 * Implements hook_theme().
 */
function az_book_theme() {
  return [
    'az_book_navigation' => [
      'variables' => [
        'book_title' => '',
        'book_url' => '',
        'book_pages' => [],
        'book_id' => '',
        'book_title_classes' => false,
        'group_id' => '',
        'group_name' => '',
        'group_url' => '',
        'group_logo_url' => false,
        'group_links' => false,
        'hide_unpublished' => false,
        'misc_links' => false,
        'status' => false,
      ],
    ],
  ];
}

