<?php


/**
 * Implements hook_theme().
 */
function az_book_theme() {
  return [
    'az_book_navigation' => [
      'variables' => [
        'book_title' => '',
        'book_url' => '',
        'book_pages' => [],
        'group_id' => '',
        'group_name' => '',
        'group_url' => '',
        'hide_unpublished' => false,
        'show_atomizer' => false,
      ],
    ],
  ];
}

function az_book_preprocess_node(&$variables) {
  $node = $variables['node'];

  switch ($node->getType()) {
     case 'article':
     case 'user_page':
     case 'book':
       $block_entity = Drupal\block\Entity\Block::load('azbooknavigation');
       $variables['block_booknavigation'] = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block_entity);
       break;
  }
}

